"""add chunk_embeddings table

Revision ID: 8473d3d61774
Revises: af9f4d4c8e2c
Create Date: 2026-10-07 17:51:42.417200+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8473d3d61774'
down_revision: Union[str, None] = 'af9f4d4c8e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_embeddings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_id', sa.BigInteger(), nullable=False),
    # 384 is written out rather than imported from the model: a migration
    # records the schema as it was, and must not change if the model does.
    sa.Column('embedding', Vector(384), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('service_id', sa.BigInteger(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('specialties', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['content_chunks.id'], name=op.f('fk_chunk_embeddings_chunk_id_content_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_chunk_embeddings_service_id_services'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk_embeddings')),
    sa.UniqueConstraint('chunk_id', name=op.f('uq_chunk_embeddings_chunk_id'))
    )
    op.create_index(op.f('ix_chunk_embeddings_service_id'), 'chunk_embeddings', ['service_id'], unique=False)
    # No vector (HNSW) index on purpose. One clinic's catalogue is small
    # enough to compare every vector exactly, and an approximate index
    # applies WHERE filters after its scan, so with the published filter it
    # can return fewer than k results.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_embeddings_service_id'), table_name='chunk_embeddings')
    op.drop_table('chunk_embeddings')
    # ### end Alembic commands ###
