"""add visits table

Revision ID: b68eafc19baa
Revises: d5dc2c15adf9
Create Date: 2026-09-01 18:01:30.889170+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68eafc19baa'
down_revision: Union[str, None] = 'd5dc2c15adf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('appointment_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('CHECKED_IN', 'IN_PROGRESS', 'COMPLETED', name='status', native_enum=False, create_constraint=True), server_default='CHECKED_IN', nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_visits_appointment_id_appointments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visits')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_visits_appointment_id'))
    )
    op.create_index(op.f('ix_visits_status'), 'visits', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_status'), table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
