"""add analytics_daily table

Revision ID: 78871e94984b
Revises: b3553e40d366
Create Date: 2026-09-07 14:41:29.753163+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78871e94984b'
down_revision: Union[str, None] = 'b3553e40d366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('appointments_booked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completed_visits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cancellations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_wait_seconds', sa.Float(), nullable=True),
    sa.Column('failed_jobs_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_analytics_daily'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics_daily')
    # ### end Alembic commands ###
