"""add billing table

Revision ID: d3c483559f81
Revises: c2c7d51e4146
Create Date: 2026-08-31 13:29:00.066392+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c483559f81'
down_revision: Union[str, None] = 'c2c7d51e4146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('appointment_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CHECKED', 'FAILED', 'REFUNDED', name='status', native_enum=False, create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_billing_appointment_id_appointments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_billing_appointment_id')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_billing_idempotency_key'))
    )
    op.create_index(op.f('ix_billing_status'), 'billing', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_status'), table_name='billing')
    op.drop_table('billing')
    # ### end Alembic commands ###
