"""add slot_reservations table

Revision ID: 8eb1eb2182b2
Revises: d3c483559f81
Create Date: 2026-08-31 15:00:29.661668+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb1eb2182b2'
down_revision: Union[str, None] = 'd3c483559f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_reservations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('appointment_id', sa.BigInteger(), nullable=False),
    sa.Column('slot_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('RESERVED', 'RELEASED', 'COMMITTED', name='status', native_enum=False, create_constraint=True), server_default='RESERVED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_slot_reservations_appointment_id_appointments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], name=op.f('fk_slot_reservations_slot_id_slots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slot_reservations'))
    )
    op.create_index(op.f('ix_slot_reservations_appointment_id'), 'slot_reservations', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_slot_reservations_slot_id'), 'slot_reservations', ['slot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slot_reservations_slot_id'), table_name='slot_reservations')
    op.drop_index(op.f('ix_slot_reservations_appointment_id'), table_name='slot_reservations')
    op.drop_table('slot_reservations')
    # ### end Alembic commands ###
