"""add waitlist table

Revision ID: d5dc2c15adf9
Revises: 8eb1eb2182b2
Create Date: 2026-08-31 19:46:04.707893+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5dc2c15adf9'
down_revision: Union[str, None] = '8eb1eb2182b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'OFFERED', name='status', native_enum=False, create_constraint=True), server_default='WAITING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_waitlist_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_waitlist_provider_id_providers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waitlist'))
    )
    op.create_index(op.f('ix_waitlist_patient_id'), 'waitlist', ['patient_id'], unique=False)
    op.create_index(op.f('ix_waitlist_provider_id'), 'waitlist', ['provider_id'], unique=False)
    op.create_index(op.f('ix_waitlist_status'), 'waitlist', ['status'], unique=False)
    op.create_index('uq_waitlist_one_waiting_entry', 'waitlist', ['provider_id', 'patient_id'], unique=True, postgresql_where=sa.text("status = 'WAITING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_waitlist_one_waiting_entry', table_name='waitlist', postgresql_where=sa.text("status = 'WAITING'"))
    op.drop_index(op.f('ix_waitlist_status'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_provider_id'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_patient_id'), table_name='waitlist')
    op.drop_table('waitlist')
    # ### end Alembic commands ###
