"""add content_chunks table

Revision ID: 88e7ca23407e
Revises: b5f5d4c068a3
Create Date: 2026-08-30 11:22:15.626325+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e7ca23407e'
down_revision: Union[str, None] = 'b5f5d4c068a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_chunks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.Enum('SERVICE', name='source_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_chunks')),
    sa.UniqueConstraint('source_type', 'source_id', 'chunk_index', name=op.f('uq_content_chunks_source_type_source_id_chunk_index'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_chunks')
    # ### end Alembic commands ###
