"""reshape analytics_daily for incremental maintenance

Revision ID: af9f4d4c8e2c
Revises: 614a60dcae54
Create Date: 2026-09-09 13:05:06.887951+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af9f4d4c8e2c"
down_revision: Union[str, None] = "614a60dcae54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analytics_daily",
        sa.Column("wait_seconds_total", sa.Float(), server_default="0", nullable=False),
    )
    op.add_column(
        "analytics_daily",
        sa.Column("wait_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.drop_column("analytics_daily", "failed_jobs_count")
    op.drop_column("analytics_daily", "avg_wait_seconds")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analytics_daily",
        sa.Column(
            "avg_wait_seconds",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "analytics_daily",
        sa.Column(
            "failed_jobs_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("analytics_daily", "wait_count")
    op.drop_column("analytics_daily", "wait_seconds_total")
    # ### end Alembic commands ###
